In [1]:
import pandas as pd

In [2]:
heart = pd.read_csv('heartDisease.csv')
heart.head()

,Disease,Age,Sex,ind_typ_angina,ind_atyp_angina,ind_non_ang_pain,resting_BP,Serum_cholest,blood_sugar_exc120,Max_heart_rate,ind_exerc_angina,ST_dep_by_exerc,ind_for_slope_up_exerc,ind_for_slope_down_exerc,num_vessels_fluro,Thal_rev_defect,Thal_fixed_defect
0,-1,63,1,1,0,0,145,233,1,150,0,2.3,0,1,0,0,1
1,1,67,1,0,0,0,160,286,0,108,1,1.5,0,0,3,0,0
2,1,67,1,0,0,0,120,229,0,129,1,2.6,0,0,2,1,0
3,-1,37,1,0,0,1,130,250,0,187,0,3.5,0,1,0,0,0
4,-1,41,0,0,1,0,130,204,0,172,0,1.4,1,0,0,0,0

In [3]:
# Sick?：0 NO，1 YES
disease = heart['Disease']
for x in disease.index:
    if x == -1:
        disease[x] = 0
heart_new = heart.drop('Disease', axis=1)
heart_new['Disease'] = disease

In [4]:
# Angina type  1typical Angina 2atypical Angina 3non Angina 4asymptomatic
angina = heart_new['ind_typ_angina']
angina = angina.copy()
for x in heart_new.index:
    if heart_new.loc[x, 'ind_typ_angina'] == 1:  # typical Angina
        angina[x] = 1
    elif heart_new.loc[x, 'ind_atyp_angina'] == 1:  # atypical Angina
        angina[x] = 2
    elif heart_new.loc[x, 'ind_non_ang_pain'] == 1:  # non Angina
        angina[x] = 3
    else:
        angina[x] = 0  # asymptomatic
heart_new['Angina'] = angina
heart_new = heart_new.drop(['ind_typ_angina', 'ind_atyp_angina', 'ind_non_ang_pain'], axis=1)
# heart_new

In [5]:
# ST-segment peak slop 1ope，-1down，0flat
slop = heart_new['ind_for_slope_up_exerc']
slop = slop.copy()
for x in heart_new.index:
    if heart_new.loc[x, 'ind_for_slope_down_exerc'] == 1:
        slop[x] = -1
heart_new = heart_new.drop('ind_for_slope_down_exerc', axis=1)
heart_new['ind_for_slope_up_exerc'] = slop

In [6]:
# Thalassemia types 1reversible 2fixed 0normal
thal = heart_new['Thal_rev_defect']
thal = thal.copy()
for x in heart_new.index:
    if heart_new.loc[x, 'Thal_fixed_defect'] == 1:
        thal[x] = 2
heart_new['Thal_rev_defect'] = thal
heart_new = heart_new.drop('Thal_fixed_defect', axis=1)

In [7]:
# reindex
heart_new = heart_new.rename(columns={'Angina': 'Angina_type', 'ind_for_slope_up_exerc': 'ind_for_slope_exerc',
                                      'Thal_rev_defect': 'Thal_defect'})
heart_new = heart_new.reindex(['Age', 'Sex', 'resting_BP', 'Serum_cholest', 'blood_sugar_exc120',
                               'Max_heart_rate', 'ind_exerc_angina', 'Angina_type', 'ST_dep_by_exerc',
                               'ind_for_slope_exerc', 'num_vessels_fluro',
                               'Thal_defect', 'Disease'], axis=1)
heart_new.to_csv('heartDieasePreprocess.csv', index = False)

In [8]:
heart_new.head()

,Age,Sex,resting_BP,Serum_cholest,blood_sugar_exc120,Max_heart_rate,ind_exerc_angina,Angina_type,ST_dep_by_exerc,ind_for_slope_exerc,num_vessels_fluro,Thal_defect,Disease
0,63,1,145,233,1,150,0,1,2.3,-1,0,2,-1
1,67,1,160,286,0,108,1,0,1.5,0,3,0,1
2,67,1,120,229,0,129,1,0,2.6,0,2,1,1
3,37,1,130,250,0,187,0,3,3.5,-1,0,0,-1
4,41,0,130,204,0,172,0,2,1.4,1,0,0,-1